.PHONY: clean All

All:
	@echo "----------Building project:[ HWTJ - Debug ]----------"
	@"$(MAKE)" -f  "HWTJ.mk"
clean:
	@echo "----------Cleaning project:[ HWTJ - Debug ]----------"
	@"$(MAKE)" -f  "HWTJ.mk" clean
